import { Router } from "express";
import { confirmPayment, getDashboard, getFaculty, getPayments, getRegistrations, login, resendPaymentConfirmationEmail, updateRegistration } from "../controllers/adminController.js";
import { getEvaluationSettings, listSubmissions, retrySelectionEmail, saveEvaluation, streamSubmissionPdf, updateEvaluationSettings } from "../controllers/evaluationController.js";
import { updatePaymentSettings } from "../controllers/paymentSettingsController.js";
import { bulkDeleteTeams, bulkUpdateTeams, deleteTeam } from "../controllers/teamManagementController.js";
import { decideRound, listRoundSelection, retryRoundEmail } from "../controllers/roundSelectionController.js";
import { listRounds, resendRoundEmail, updateRounds } from "../controllers/roundsController.js";
import { requireAdmin } from "../middleware/authMiddleware.js";

const router = Router();
router.post("/login", login);
router.use(requireAdmin);
router.get("/dashboard", getDashboard);
router.get("/registrations", getRegistrations);
router.put("/registrations/:id", updateRegistration);
router.delete("/registrations/:id", deleteTeam);
router.post("/registrations/bulk-delete", bulkDeleteTeams);
router.post("/registrations/bulk-update", bulkUpdateTeams);
router.get("/payments", getPayments);
router.get("/payment-history", getPayments);
router.put("/payments/:id/confirm", confirmPayment);
router.post("/payments/:id/resend-email", resendPaymentConfirmationEmail);
router.get("/faculty", getFaculty);
router.put("/payment-settings", updatePaymentSettings);
router.get("/pdf-submissions", listSubmissions);
router.get("/pdf-submissions/:id/pdf", streamSubmissionPdf);
router.put("/pdf-submissions/:id/evaluation", saveEvaluation);
router.post("/pdf-submissions/:id/selection-email", retrySelectionEmail);
router.get("/round-selection", listRoundSelection);
router.put("/round-selection/:id", decideRound);
router.post("/round-selection/:id/email", retryRoundEmail);
router.get("/rounds", listRounds);
router.put("/rounds/:id", updateRounds);
router.post("/rounds/:id/email", resendRoundEmail);
router.get("/evaluation-settings", getEvaluationSettings);
router.put("/evaluation-settings", updateEvaluationSettings);
export default router;
